[package]
name = "overr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trait-def = { version = "0.1.0", path = "../trait-def" }
under = { version = "0.1.0", path = "../under" }
